version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Go tests
          command: go test -v ./...
      - run:
          name: Is code formatted
          command: |
            if [[ $(go fmt ./...) ]]; then
              echo -e "\e[31m Please format your changes. \e[0m"
                exit 1
            fi
